### ISSUE TITLE
test utf-8 encoding

### ISSUE THREAD

**Issue by Payzman** [Payzman/Learning-Python#83]
## **Condition: closed**
#82 
### **TODO**
- [ ] build string with special character in it
- [ ] convert string to bytes via encode
- [ ] print bytes to console
